# Generated by Django 2.0.3 on 2018-03-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200, verbose_name='Название программы')),
                ('certificate_number', models.CharField(max_length=200, verbose_name='Номер')),
                ('status', models.CharField(max_length=200, verbose_name='Статус сертификата')),
            ],
            options={
                'verbose_name': 'сертификат',
                'verbose_name_plural': 'сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200, verbose_name='Название программы')),
                ('group_name', models.CharField(max_length=100, verbose_name='Номер группы')),
                ('begin_date', models.DateTimeField(verbose_name='Дата начала курса')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания курса')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.TextField(max_length=500, verbose_name='ФИО')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, unique=True, verbose_name='Пароль')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sertificate.Group')),
            ],
            options={
                'verbose_name': 'обучающийся',
                'verbose_name_plural': 'обучающиеся',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.TextField(max_length=500, verbose_name='ФИО')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, unique=True, verbose_name='Пароль')),
                ('group', models.ManyToManyField(to='Sertificate.Group')),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sertificate.Student'),
        ),
    ]
