# Generated by Django 2.0.3 on 2018-05-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sertificate', '0003_auto_20180504_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200, verbose_name='Название программы')),
                ('num_hours', models.IntegerField(default=1, verbose_name='Количество часов')),
            ],
            options={
                'verbose_name': 'программа',
                'verbose_name_plural': 'программы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200, verbose_name='Задание')),
                ('task_num', models.IntegerField(default=1, verbose_name='Номер задания')),
                ('task_description', models.TextField(verbose_name='Описание задания')),
                ('program', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sertificate.Program')),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'задания',
            },
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='group_number',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='program_name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='program_name',
        ),
        migrations.AddField(
            model_name='certificate',
            name='program',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sertificate.Program'),
        ),
        migrations.AddField(
            model_name='group',
            name='program',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sertificate.Program'),
        ),
    ]
