# Generated by Django 2.0.3 on 2018-05-24 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sertificate', '0004_auto_20180517_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_description',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='program',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sertificate.Program', verbose_name='Программа обучения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='program',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sertificate.Program', verbose_name='Программа обучения'),
        ),
    ]
