# Generated by Django 2.0.3 on 2018-05-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sertificate', '0005_auto_20180524_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='begin_date',
            field=models.DateField(verbose_name='Дата начала курса'),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания курса'),
        ),
    ]
