# Generated by Django 2.0.3 on 2018-05-30 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sertificate', '0006_auto_20180528_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='change',
            field=models.BooleanField(default=True, verbose_name='Возможны ли изменения'),
        ),
        migrations.AlterField(
            model_name='group',
            name='program',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sertificate.Program', verbose_name='Программа обучения'),
        ),
    ]
