# Generated by Django 2.0.3 on 2018-06-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sertificate', '0008_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='status',
        ),
        migrations.AddField(
            model_name='certificate',
            name='docs',
            field=models.BooleanField(default=False, verbose_name='Сданы документы'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='pay',
            field=models.BooleanField(default=False, verbose_name='Произведена оплата'),
        ),
        migrations.AddField(
            model_name='result',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Выполнены необходимые задания'),
        ),
    ]
