# Generated by Django 2.0.3 on 2018-06-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sertificate', '0009_auto_20180602_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(default='create', max_length=200, verbose_name='Статус сертификата'),
        ),
    ]
