# Generated by Django 2.0.3 on 2018-06-07 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sertificate', '0010_certificate_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'результат', 'verbose_name_plural': 'результаты'},
        ),
        migrations.AddField(
            model_name='result',
            name='hash',
            field=models.CharField(default='', max_length=500, verbose_name='Хеш-код'),
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обучающийся'),
        ),
        migrations.AlterField(
            model_name='result',
            name='task',
            field=models.ManyToManyField(blank=True, to='Sertificate.Task', verbose_name='Выполненные задания'),
        ),
    ]
