# Generated by Django 2.0.3 on 2018-06-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sertificate', '0011_auto_20180607_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='hash',
        ),
        migrations.AddField(
            model_name='certificate',
            name='hash',
            field=models.CharField(default='', max_length=500, verbose_name='Хеш-код'),
        ),
    ]
