# Generated by Django 2.0.3 on 2018-06-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sertificate', '0012_auto_20180607_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='change',
        ),
    ]
