# Generated by Django 2.0.3 on 2018-06-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sertificate', '0013_remove_certificate_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(max_length=200, verbose_name='Регистрационный номер'),
        ),
    ]
