# Generated by Django 2.0.3 on 2018-05-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sertificate', '0004_auto_20180517_1715'),
        ('userprofile', '0003_auto_20180504_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='task',
            field=models.ManyToManyField(default=0, to='Sertificate.Task', verbose_name='Решенные задания'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sertificate.Group', verbose_name='Группа'),
        ),
    ]
