# Generated by Django 2.0.3 on 2018-05-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20180517_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='task',
            field=models.ManyToManyField(null=True, to='Sertificate.Task', verbose_name='Решенные задания'),
        ),
    ]
