# Generated by Django 2.0.3 on 2018-05-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20180517_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sertificate.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='task',
            field=models.ManyToManyField(blank=True, to='Sertificate.Task', verbose_name='Решенные задания'),
        ),
    ]
