# Generated by Django 2.0.3 on 2018-05-24 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sertificate', '0005_auto_20180524_1352'),
        ('userprofile', '0006_auto_20180524_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='group',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group_for_stud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sertificate.Group', verbose_name='Группа (для студентов)'),
        ),
    ]
