# Generated by Django 2.0.3 on 2018-06-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20180524_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='task',
        ),
    ]
